name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: internal-sandbox-446612
  REGION: asia-south1
  REPO: my-repo
  IMAGE: devops-app
  CLUSTER: my-cluster
  ZONE: asia-south1-a

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project $PROJECT_ID

    - name: Configure Docker
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev -q

    - name: Build Docker Image
      run: |
        docker -v
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }}

    - name: Install kubectl
      run: |
        gcloud components install kubectl -q

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials $CLUSTER --zone $ZONE

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/devops-app devops-app=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:${{ github.sha }}
        kubectl rollout status deployment/devops-app
